// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/Govorov1705/avito-pvz/internal/dtos"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Govorov1705/avito-pvz/internal/models"
)

// MockPvzRepository is an autogenerated mock type for the PvzRepository type
type MockPvzRepository struct {
	mock.Mock
}

type MockPvzRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPvzRepository) EXPECT() *MockPvzRepository_Expecter {
	return &MockPvzRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, dto
func (_m *MockPvzRepository) Add(ctx context.Context, dto *dtos.CreatePvzRequest) (*models.Pvz, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Pvz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.CreatePvzRequest) (*models.Pvz, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.CreatePvzRequest) *models.Pvz); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Pvz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.CreatePvzRequest) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvzRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockPvzRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - dto *dtos.CreatePvzRequest
func (_e *MockPvzRepository_Expecter) Add(ctx interface{}, dto interface{}) *MockPvzRepository_Add_Call {
	return &MockPvzRepository_Add_Call{Call: _e.mock.On("Add", ctx, dto)}
}

func (_c *MockPvzRepository_Add_Call) Run(run func(ctx context.Context, dto *dtos.CreatePvzRequest)) *MockPvzRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dtos.CreatePvzRequest))
	})
	return _c
}

func (_c *MockPvzRepository_Add_Call) Return(_a0 *models.Pvz, _a1 error) *MockPvzRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvzRepository_Add_Call) RunAndReturn(run func(context.Context, *dtos.CreatePvzRequest) (*models.Pvz, error)) *MockPvzRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockPvzRepository) List(ctx context.Context) ([]*models.Pvz, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Pvz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Pvz, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Pvz); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Pvz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvzRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPvzRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPvzRepository_Expecter) List(ctx interface{}) *MockPvzRepository_List_Call {
	return &MockPvzRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPvzRepository_List_Call) Run(run func(ctx context.Context)) *MockPvzRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPvzRepository_List_Call) Return(_a0 []*models.Pvz, _a1 error) *MockPvzRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvzRepository_List_Call) RunAndReturn(run func(context.Context) ([]*models.Pvz, error)) *MockPvzRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithPagination provides a mock function with given fields: ctx, page, limit
func (_m *MockPvzRepository) ListWithPagination(ctx context.Context, page int, limit int) ([]*models.Pvz, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListWithPagination")
	}

	var r0 []*models.Pvz
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Pvz, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Pvz); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Pvz)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvzRepository_ListWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithPagination'
type MockPvzRepository_ListWithPagination_Call struct {
	*mock.Call
}

// ListWithPagination is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockPvzRepository_Expecter) ListWithPagination(ctx interface{}, page interface{}, limit interface{}) *MockPvzRepository_ListWithPagination_Call {
	return &MockPvzRepository_ListWithPagination_Call{Call: _e.mock.On("ListWithPagination", ctx, page, limit)}
}

func (_c *MockPvzRepository_ListWithPagination_Call) Run(run func(ctx context.Context, page int, limit int)) *MockPvzRepository_ListWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockPvzRepository_ListWithPagination_Call) Return(_a0 []*models.Pvz, _a1 error) *MockPvzRepository_ListWithPagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvzRepository_ListWithPagination_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Pvz, error)) *MockPvzRepository_ListWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPvzRepository creates a new instance of MockPvzRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPvzRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPvzRepository {
	mock := &MockPvzRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
