// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Govorov1705/avito-pvz/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, productType, receptionId
func (_m *MockProductRepository) Add(ctx context.Context, productType models.ProductType, receptionId uuid.UUID) (*models.Product, error) {
	ret := _m.Called(ctx, productType, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ProductType, uuid.UUID) (*models.Product, error)); ok {
		return rf(ctx, productType, receptionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ProductType, uuid.UUID) *models.Product); ok {
		r0 = rf(ctx, productType, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ProductType, uuid.UUID) error); ok {
		r1 = rf(ctx, productType, receptionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockProductRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - productType models.ProductType
//   - receptionId uuid.UUID
func (_e *MockProductRepository_Expecter) Add(ctx interface{}, productType interface{}, receptionId interface{}) *MockProductRepository_Add_Call {
	return &MockProductRepository_Add_Call{Call: _e.mock.On("Add", ctx, productType, receptionId)}
}

func (_c *MockProductRepository_Add_Call) Run(run func(ctx context.Context, productType models.ProductType, receptionId uuid.UUID)) *MockProductRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ProductType), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_Add_Call) Return(_a0 *models.Product, _a1 error) *MockProductRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Add_Call) RunAndReturn(run func(context.Context, models.ProductType, uuid.UUID) (*models.Product, error)) *MockProductRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, productId
func (_m *MockProductRepository) Delete(ctx context.Context, productId uuid.UUID) error {
	ret := _m.Called(ctx, productId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, productId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - productId uuid.UUID
func (_e *MockProductRepository_Expecter) Delete(ctx interface{}, productId interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, productId)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(ctx context.Context, productId uuid.UUID)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(_a0 error) *MockProductRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastByReceptionId provides a mock function with given fields: ctx, receptionId
func (_m *MockProductRepository) GetLastByReceptionId(ctx context.Context, receptionId uuid.UUID) (*models.Product, error) {
	ret := _m.Called(ctx, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for GetLastByReceptionId")
	}

	var r0 *models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Product, error)); ok {
		return rf(ctx, receptionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Product); ok {
		r0 = rf(ctx, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, receptionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetLastByReceptionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastByReceptionId'
type MockProductRepository_GetLastByReceptionId_Call struct {
	*mock.Call
}

// GetLastByReceptionId is a helper method to define mock.On call
//   - ctx context.Context
//   - receptionId uuid.UUID
func (_e *MockProductRepository_Expecter) GetLastByReceptionId(ctx interface{}, receptionId interface{}) *MockProductRepository_GetLastByReceptionId_Call {
	return &MockProductRepository_GetLastByReceptionId_Call{Call: _e.mock.On("GetLastByReceptionId", ctx, receptionId)}
}

func (_c *MockProductRepository_GetLastByReceptionId_Call) Run(run func(ctx context.Context, receptionId uuid.UUID)) *MockProductRepository_GetLastByReceptionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_GetLastByReceptionId_Call) Return(_a0 *models.Product, _a1 error) *MockProductRepository_GetLastByReceptionId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetLastByReceptionId_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Product, error)) *MockProductRepository_GetLastByReceptionId_Call {
	_c.Call.Return(run)
	return _c
}

// ListByReceptionIds provides a mock function with given fields: ctx, receptionIds
func (_m *MockProductRepository) ListByReceptionIds(ctx context.Context, receptionIds []*uuid.UUID) ([]*models.Product, error) {
	ret := _m.Called(ctx, receptionIds)

	if len(ret) == 0 {
		panic("no return value specified for ListByReceptionIds")
	}

	var r0 []*models.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*uuid.UUID) ([]*models.Product, error)); ok {
		return rf(ctx, receptionIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*uuid.UUID) []*models.Product); ok {
		r0 = rf(ctx, receptionIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*uuid.UUID) error); ok {
		r1 = rf(ctx, receptionIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_ListByReceptionIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByReceptionIds'
type MockProductRepository_ListByReceptionIds_Call struct {
	*mock.Call
}

// ListByReceptionIds is a helper method to define mock.On call
//   - ctx context.Context
//   - receptionIds []*uuid.UUID
func (_e *MockProductRepository_Expecter) ListByReceptionIds(ctx interface{}, receptionIds interface{}) *MockProductRepository_ListByReceptionIds_Call {
	return &MockProductRepository_ListByReceptionIds_Call{Call: _e.mock.On("ListByReceptionIds", ctx, receptionIds)}
}

func (_c *MockProductRepository_ListByReceptionIds_Call) Run(run func(ctx context.Context, receptionIds []*uuid.UUID)) *MockProductRepository_ListByReceptionIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*uuid.UUID))
	})
	return _c
}

func (_c *MockProductRepository_ListByReceptionIds_Call) Return(_a0 []*models.Product, _a1 error) *MockProductRepository_ListByReceptionIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_ListByReceptionIds_Call) RunAndReturn(run func(context.Context, []*uuid.UUID) ([]*models.Product, error)) *MockProductRepository_ListByReceptionIds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
