// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/Govorov1705/avito-pvz/internal/dtos"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Govorov1705/avito-pvz/internal/models"

	time "time"

	uuid "github.com/google/uuid"
)

// MockReceptionRepository is an autogenerated mock type for the ReceptionRepository type
type MockReceptionRepository struct {
	mock.Mock
}

type MockReceptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReceptionRepository) EXPECT() *MockReceptionRepository_Expecter {
	return &MockReceptionRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, dto
func (_m *MockReceptionRepository) Add(ctx context.Context, dto *dtos.CreateReceptionRequest) (*models.Reception, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 *models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.CreateReceptionRequest) (*models.Reception, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.CreateReceptionRequest) *models.Reception); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dtos.CreateReceptionRequest) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReceptionRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockReceptionRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - dto *dtos.CreateReceptionRequest
func (_e *MockReceptionRepository_Expecter) Add(ctx interface{}, dto interface{}) *MockReceptionRepository_Add_Call {
	return &MockReceptionRepository_Add_Call{Call: _e.mock.On("Add", ctx, dto)}
}

func (_c *MockReceptionRepository_Add_Call) Run(run func(ctx context.Context, dto *dtos.CreateReceptionRequest)) *MockReceptionRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dtos.CreateReceptionRequest))
	})
	return _c
}

func (_c *MockReceptionRepository_Add_Call) Return(_a0 *models.Reception, _a1 error) *MockReceptionRepository_Add_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReceptionRepository_Add_Call) RunAndReturn(run func(context.Context, *dtos.CreateReceptionRequest) (*models.Reception, error)) *MockReceptionRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx, receptionId
func (_m *MockReceptionRepository) Close(ctx context.Context, receptionId uuid.UUID) (*models.Reception, error) {
	ret := _m.Called(ctx, receptionId)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 *models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Reception, error)); ok {
		return rf(ctx, receptionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Reception); ok {
		r0 = rf(ctx, receptionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, receptionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReceptionRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReceptionRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
//   - receptionId uuid.UUID
func (_e *MockReceptionRepository_Expecter) Close(ctx interface{}, receptionId interface{}) *MockReceptionRepository_Close_Call {
	return &MockReceptionRepository_Close_Call{Call: _e.mock.On("Close", ctx, receptionId)}
}

func (_c *MockReceptionRepository_Close_Call) Run(run func(ctx context.Context, receptionId uuid.UUID)) *MockReceptionRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReceptionRepository_Close_Call) Return(_a0 *models.Reception, _a1 error) *MockReceptionRepository_Close_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReceptionRepository_Close_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Reception, error)) *MockReceptionRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetOpenByPvzId provides a mock function with given fields: ctx, pvzId
func (_m *MockReceptionRepository) GetOpenByPvzId(ctx context.Context, pvzId uuid.UUID) (*models.Reception, error) {
	ret := _m.Called(ctx, pvzId)

	if len(ret) == 0 {
		panic("no return value specified for GetOpenByPvzId")
	}

	var r0 *models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Reception, error)); ok {
		return rf(ctx, pvzId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Reception); ok {
		r0 = rf(ctx, pvzId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pvzId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReceptionRepository_GetOpenByPvzId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOpenByPvzId'
type MockReceptionRepository_GetOpenByPvzId_Call struct {
	*mock.Call
}

// GetOpenByPvzId is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzId uuid.UUID
func (_e *MockReceptionRepository_Expecter) GetOpenByPvzId(ctx interface{}, pvzId interface{}) *MockReceptionRepository_GetOpenByPvzId_Call {
	return &MockReceptionRepository_GetOpenByPvzId_Call{Call: _e.mock.On("GetOpenByPvzId", ctx, pvzId)}
}

func (_c *MockReceptionRepository_GetOpenByPvzId_Call) Run(run func(ctx context.Context, pvzId uuid.UUID)) *MockReceptionRepository_GetOpenByPvzId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockReceptionRepository_GetOpenByPvzId_Call) Return(_a0 *models.Reception, _a1 error) *MockReceptionRepository_GetOpenByPvzId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReceptionRepository_GetOpenByPvzId_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Reception, error)) *MockReceptionRepository_GetOpenByPvzId_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPvzIdsWithDateRange provides a mock function with given fields: ctx, pvzIds, startDate, endDate
func (_m *MockReceptionRepository) ListByPvzIdsWithDateRange(ctx context.Context, pvzIds []*uuid.UUID, startDate time.Time, endDate time.Time) ([]*models.Reception, error) {
	ret := _m.Called(ctx, pvzIds, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for ListByPvzIdsWithDateRange")
	}

	var r0 []*models.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*uuid.UUID, time.Time, time.Time) ([]*models.Reception, error)); ok {
		return rf(ctx, pvzIds, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*uuid.UUID, time.Time, time.Time) []*models.Reception); ok {
		r0 = rf(ctx, pvzIds, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*uuid.UUID, time.Time, time.Time) error); ok {
		r1 = rf(ctx, pvzIds, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReceptionRepository_ListByPvzIdsWithDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPvzIdsWithDateRange'
type MockReceptionRepository_ListByPvzIdsWithDateRange_Call struct {
	*mock.Call
}

// ListByPvzIdsWithDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - pvzIds []*uuid.UUID
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockReceptionRepository_Expecter) ListByPvzIdsWithDateRange(ctx interface{}, pvzIds interface{}, startDate interface{}, endDate interface{}) *MockReceptionRepository_ListByPvzIdsWithDateRange_Call {
	return &MockReceptionRepository_ListByPvzIdsWithDateRange_Call{Call: _e.mock.On("ListByPvzIdsWithDateRange", ctx, pvzIds, startDate, endDate)}
}

func (_c *MockReceptionRepository_ListByPvzIdsWithDateRange_Call) Run(run func(ctx context.Context, pvzIds []*uuid.UUID, startDate time.Time, endDate time.Time)) *MockReceptionRepository_ListByPvzIdsWithDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*uuid.UUID), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockReceptionRepository_ListByPvzIdsWithDateRange_Call) Return(_a0 []*models.Reception, _a1 error) *MockReceptionRepository_ListByPvzIdsWithDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReceptionRepository_ListByPvzIdsWithDateRange_Call) RunAndReturn(run func(context.Context, []*uuid.UUID, time.Time, time.Time) ([]*models.Reception, error)) *MockReceptionRepository_ListByPvzIdsWithDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReceptionRepository creates a new instance of MockReceptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReceptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReceptionRepository {
	mock := &MockReceptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
